---
title: "Tutorial for DexTRAC"
---

# Loading
```{r}
require(tidyverse)
require(checkmate)
require(ggrepel)
require(ggtext)
require(JasonToolBox)
require(fitdistrplus)
data_dir = './data/'
# run setwd('~/data/projects/09.Niehu_HBVHCC/') in the command line
meta_tbl = read_csv(sprintf('%s/hbv_hcc_cohor2.rna_tcr_dex.csv', data_dir))
colnames(meta_tbl)[1] = 'cellID'

source('R/utils.R')
```

```{r}
var_clone_id = 'clone.id'
var_patient_id = 'patient'
atbd_names = str_extract(pattern = '^HBVgp.*', colnames(meta_tbl)) %>% .[!is.na(.)]
gpexpr_mt = as.matrix(meta_tbl[, atbd_names])
rownames(gpexpr_mt) = meta_tbl$cellID
gpexpr_mt[is.na(gpexpr_mt)] = 0
celltype_vec = with(meta_tbl, setNames(nm = cellID, major_cluster))
major_celltype_vec = setNames(nm = names(celltype_vec), celltype_vec %>% str_extract(pattern = '^[^_]+'))
checkmate::assert(all(meta_tbl$`CD4/CD8` == major_celltype_vec))

tmp_meta = unique(meta_tbl[, c(var_clone_id, var_patient_id)])
clone2pat_vec = setNames(nm = tmp_meta[[var_clone_id]], tmp_meta[[var_patient_id]]) 




cloneid_vec = with(meta_tbl, setNames(nm = cellID, meta_tbl$clone.id))
clonesize_vec = meta_tbl %>% dplyr::select(clone.id, clone.size) %>% distinct() %>% deframe
CD8clonesize_vec = meta_tbl %>% dplyr::filter(major_cluster == 'CD8') %>% pull(clone.id) %>% table

```

# Determine cutoff for each antibody
```{r}
target_cells = names(major_celltype_vec)[major_celltype_vec != 'CD4']
gpexpr_lst = estimate_truecounts(gpexpr_mt, experiment_cells = target_cells, ctrl_p_cutoff = 0.0005)
```

## Visualization
```{r, fig.width=8, fig.height=5}
theme_set(theme_classic(base_size = 20))
target_atbd = 'HBVgp2_aagc_env'
target_obj = gpexpr_lst[[target_atbd]]
p1 = ggplot(target_obj$plt_df, aes(x = x, fill = group)) +
  geom_bar(position = position_dodge2(preserve = 'single')) +
  geom_vline(xintercept = target_obj$cutoff + 0.5, linetype = 2) +
  scale_y_log10() +
  labs(
    title = sprintf('Target antigen = \n%s\ncutoff = %d', target_atbd, target_obj$cutoff),
    x = "Number of antibody counts",
    y = "Number of cells",
    fill = 'Group'
  ) +
  theme(title = element_text(size = 15))
p1

plot(target_obj$fit_res)

```


# Calculate enrichment for clonotypes and antigens
```{r}
pval_df = estimate_enrichment(gpexpr_lst, target_cells, cloneid_vec)
```

## Visualization
```{r, fig.width=12, fig.height=10}
padj_cutoff = 0.1
breaks_vec = c(seq(0, -log10(padj_cutoff), 0.05), seq(-log10(padj_cutoff), -log10(0.01), 0.05)) %>% unique()
padj_mt = pval_df %>% reshape2::acast(CloneID ~ Antibody, value.var = 'Fisher.Padj')
count_vec = apply(padj_mt, 1, function(x){sum(x<padj_cutoff)})
table(count_vec)
signif_clones = rownames(padj_mt)[apply(padj_mt, 1, function(x){sum(x<padj_cutoff) > 0})]
signif_clones = names(clonesize_vec[signif_clones] %>% sort(decreasing = T))
flt_padj_mt = padj_mt[signif_clones, ]
sprintf('Number of non-specific clones: %d', nrow(padj_mt) - nrow(flt_padj_mt))


pheatmap::pheatmap(
  -log10(flt_padj_mt),
  show_rownames = T,
  cluster_cols = T,
  cluster_rows = T,
  color = colorRampPalette(rev(
    RColorBrewer::brewer.pal(n = 7, name = "RdYlBu")
  ))(length(breaks_vec)),
  breaks = breaks_vec,
  display_numbers = T,
  main = '-log10(p.adjusted)'
)

```

# Determine avidities
```{r}
avid_obj = determine_avidities(pval_df, signif_clones)


plot(avid_obj$GMMfit_obj)

plot(avid_obj$GMMfit_obj, which = 2, xlab2 = 'log10(Odd Ratios)')
lines(density(avid_obj$x), lty = 2, lwd = 2)
abline(v = avid_obj$logOR_cutoff, lty = 3, lwd = 2)

```

## Visualization of ORs
```{r, fig.width=6, fig.height=4}
avid_obj$avidity_df %>%
  filter(CloneID %in% signif_clones) %>%
  filter(Fisher.OR > 0) %>% 
  # filter(Fisher.Padj < padj_cutoff) %>%
  ggplot(aes(x = log10(Fisher.OR + 0.1))) +
  geom_histogram(aes(y = ..count.., fill = avidity), bins = 30) +
  geom_vline(xintercept = avid_obj$logOR_cutoff + 0.05, linetype = 2) +
  labs(fill = 'Avidity') +
  theme_classic(base_size = 20) + 
  scale_fill_manual(values = c('High' = "#FF5757", 'Low' = "#6557FF", 'NotSignif' = "#A3A3A3")) + 
  theme(legend.position = 'bottom')

```

## Visualization with pie chart and avidities

```{r, fig.height=10, fig.width=22}
plt_lst = list()
flt_cloneid_vec = cloneid_vec[major_celltype_vec == 'CD8']
for(t_tcr_clone in signif_clonotypes2run) {
  atbd_count_vec = bind_count_mt[names(flt_cloneid_vec)[flt_cloneid_vec == t_tcr_clone],] %>%
    apply(1, function(x) {
      x = x[x != 0]
      if (length(x) != 0) {
        max_lbl = names(x)[which(x == max(x))]
        if (length(max_lbl) > 1) {
          return('Mult')
        }
        return(max_lbl)
      } else {
        return('None')
      }
    }) %>% unlist() %>% table()
  t_clone.size = clonesize_vec[t_tcr_clone]
  atbd_count_vec = atbd_count_vec[atbd_count_vec != 0]
  atbd_count_vec = setNames(nm = names(atbd_count_vec), as.numeric(atbd_count_vec))
  
  t_plt_tbl = atbd_count_vec %>% 
    enframe(name = 'antibody', value = 'count') %>% mutate(ratio = count / t_clone.size) %>% 
    arrange(desc(ratio)) %>%
    mutate(
      csum = rev(cumsum(rev(ratio))),
      pos = ratio / 2 + lead(csum, 1),
      pos = if_else(is.na(pos), ratio / 2, pos)
    )
  
  checkmate::assert(sum(t_plt_tbl$count) == clonesize_vec[t_tcr_clone])
  
  highAff_vec = avid_obj$highAff_lst[[t_tcr_clone]]
  p1 = ggplot(t_plt_tbl, aes(
    x = '',
    y = ratio,
    fill = fct_inorder(antibody)
  )) +
    geom_col(width = 1, color = 1) +
    coord_polar(theta = 'y') +
    ggrepel::geom_label_repel(data = t_plt_tbl %>% head(5),
                     aes(y = pos, label = antibody),
                     nudge_x = 1) +
    theme_void() +
    scale_fill_manual(values = color_atbds) +
    labs(
      title = sprintf('CloneID: %s, size = %d',
                      t_tcr_clone,
                      clonesize_vec[t_tcr_clone]),
      caption = sprintf(
        "Antigen avidity: <br><span style='color:red'>%s</span><br>%s",
        paste0(names(highAff_vec)[highAff_vec == 'High'], collapse = '<br>'),
        paste0(names(highAff_vec)[highAff_vec != 'High'], collapse = '<br>')
      )
    ) +
    theme(
      legend.position = 'None',
      plot.title = element_text(hjust = 0.5),
      plot.caption = ggtext::element_markdown(hjust = 0.5, size = 14)
    )
  p1
  
  plt_lst[[t_tcr_clone]] = p1
}
patchwork::wrap_plots(plt_lst, ncol = 9)

```

# Other plots involed in the article

```{r, fig.width=6, fig.height=5}
clonal_cloneids = cloneid_vec[major_celltype_vec == 'CD8'] %>% table() %>% {.[.>1]} %>% names
sprintf('%d/%d', sum(CD8clonesize_vec[signif_clones]), sum(CD8clonesize_vec[clonal_cloneids]))

plt_clonal_tbl = tibble(
  category = c('HBV-specific', 'Unknown'),
  ratio = c(
    sum(CD8clonesize_vec[signif_clones]) / sum(CD8clonesize_vec[clonal_cloneids]),
    1 - sum(CD8clonesize_vec[signif_clones]) / sum(CD8clonesize_vec[clonal_cloneids])
  )
) %>% arrange(desc(ratio)) %>%
  mutate(
    csum = rev(cumsum(rev(ratio))),
    pos = ratio / 2 + lead(csum, 1),
    pos = if_else(is.na(pos), ratio / 2, pos)
  )


  
ggplot(plt_clonal_tbl, aes(
  x = '', y = ratio, fill = fct_inorder(category) )) +
  geom_col(width = 1, color = 1) +
  coord_polar(theta = 'y') +
  ggrepel::geom_label_repel(data = plt_clonal_tbl,
                   aes(y = pos, label = sprintf('%s: %.2f%%', category, ratio * 100)),
                   nudge_x = 1) +
  theme_void() +
  labs(title = sprintf('Percentage of HBV-specific T cells in all clonal CD8 T cells\n(n  = %d)', sum(CD8clonesize_vec[clonal_cloneids]))) +
  theme(legend.position = 'None')

```



## Manually examine single clone

```{r, fig.height=6, fig.width=6}
t_tcr_clone = 'clonotype_13'
t_signif_atbds = padj_mt[t_tcr_clone,] %>% .[. < padj_cutoff] %>% names
t_signif_atbds
clone_cells = names(flt_cloneid_vec)[flt_cloneid_vec == t_tcr_clone]


atbd_count_vec = bind_count_mt[names(flt_cloneid_vec)[flt_cloneid_vec == t_tcr_clone],] %>%
  apply(1, function(x) {
    x = x[x != 0]
    if (length(x) != 0) {
      max_lbl = names(x)[which(x == max(x))]
      if (length(max_lbl) > 1) {
        return('Mult')
      }
      return(max_lbl)
    } else {
      return('None')
    }
  }) %>% unlist() %>% table()
atbd_count_vec = atbd_count_vec[atbd_count_vec != 0]
atbd_count_vec = setNames(nm = names(atbd_count_vec), as.numeric(atbd_count_vec))

t_plt_tbl = atbd_count_vec %>% enframe(name = 'antibody', value = 'count') %>% mutate(ratio = count /
                                                                                        t_clone.size) %>% arrange(desc(ratio)) %>%
  mutate(
    csum = rev(cumsum(rev(ratio))),
    pos = ratio / 2 + lead(csum, 1),
    pos = if_else(is.na(pos), ratio / 2, pos)
  )

checkmate::assert(sum(t_plt_tbl$count) == clonesize_vec[t_tcr_clone])

highAff_vec = avid_obj$highAff_lst[[t_tcr_clone]]

ggplot(t_plt_tbl, aes(
  x = '',
  y = ratio,
  fill = fct_inorder(antibody)
)) +
  geom_col(width = 1, color = 1) +
  coord_polar(theta = 'y') +
  geom_label_repel(data = t_plt_tbl %>% head(5),
                   aes(y = pos, label = antibody),
                   nudge_x = 1) +
  theme_void() +
  scale_fill_manual(values = color_atbds) +
  labs(
    title = sprintf('CloneID: %s, size = %d',
                    # clone2pat_vec[t_tcr_clone],
                    t_tcr_clone,
                    clonesize_vec[t_tcr_clone]),
    caption = sprintf(
      "Antigen avidity: <br><span style='color:red'>%s</span><br>%s",
      paste0(names(highAff_vec)[highAff_vec == 'High'], collapse = '<br>'),
      paste0(names(highAff_vec)[highAff_vec != 'High'], collapse = '<br>')
    )
  ) +
  theme(
    legend.position = 'None',
    plot.title = element_text(hjust = 0.5),
    plot.caption = ggtext::element_markdown(hjust = 0.5, size = 14)
  )


```


## Printing for overal distribution
```{r, fig.width=7, fig.height=5}
meta_out_tbl = meta_tbl %>% 
  filter(major_cluster == 'CD8', clone.id %in% clonal_cloneids)

HBV_specifc_clones = rownames(flt_padj_mt)
Mono_reactive_clones = 
  unique(c(unlist(lapply(avid_obj$highAff_lst, function(x){sum(x == 'High') == 1})) %>% .[.] %>% names, 
    unlist(lapply(avid_obj$highAff_lst, function(x){length(x) == 1})) %>% .[.] %>% names))

High_avidity_clones = unlist(lapply(avid_obj$highAff_lst, function(x){sum(x == 'High') > 0})) %>% .[.] %>% names

meta_out_tbl = meta_out_tbl %>% mutate(
  HBV_specifc_Tcell = ifelse(clone.id %in% HBV_specifc_clones, 'HBVspecific', 'Unknown'), 
  Mono_recative = (clone.id %in% Mono_reactive_clones) & (clone.id %in% HBV_specifc_clones), 
  Cross_reactive = (!(clone.id %in% Mono_reactive_clones)) & (clone.id %in% HBV_specifc_clones), 
  High_avidity = ((clone.id %in% High_avidity_clones)) & (clone.id %in% HBV_specifc_clones), 
  Low_avidity = (!(clone.id %in% High_avidity_clones)) & (clone.id %in% HBV_specifc_clones)
)

# Distribution across different patients
meta_out_tbl %>% ggplot(aes(fill = HBV_specifc_Tcell, x = patient)) +
  geom_bar(width = 0.5) + 
  theme_classic(base_size = 20) +
  labs(x = 'Patient', y = 'Cell count', fill = 'Category') +
  scale_fill_discrete(labels = c('HBVspecific' = 'High-confidence HBV specific TCR', 'Unknown' = 'None-enriched TCR')) + 
  theme(legend.position = 'bottom') +
  guides(fill = guide_legend( ncol = 1))

# ggsave(filename = './plots/barplot_specific.pdf', width = 7, height = 5)

P16_clonesize = meta_out_tbl %>% filter(patient == 'P16') %>% dplyr::select(clone.id, clone.size) %>% distinct() %>% deframe %>% sort(decreasing = T)
head(P16_clonesize, 10)

P16_cloneids = meta_out_tbl %>% filter(patient == 'P16') %>% pull(clone.id) %>% unique()

```


## Test binding ratio between clonal clones
```{r, fig.width=6, fig.height=5}
require(ggsignif)
atbd_count_lst = pbmcapply::pbmclapply(mc.cores = 20, X = clonal_cloneids, FUN = function(t_tcr_clone ){
atbd_count_vec = bind_count_mt[names(cloneid_vec)[cloneid_vec == t_tcr_clone], ] %>% 
  apply(1, function(x) { 
    x = x[x != 0] 
    if (length(x) != 0) {
      max_lbl = names(x)[which(x == max(x))]
      if(length(max_lbl) > 1){
        return('Mult')
      }
      return(max_lbl)
    } else {
      return('None')
    }
  }) %>% unlist() %>% table() 
  atbd_count_vec = atbd_count_vec[atbd_count_vec !=0]
  atbd_count_vec = setNames(nm = names(atbd_count_vec), as.numeric(atbd_count_vec))
  
  return(atbd_count_vec['None']/sum(atbd_count_vec))
})
names(atbd_count_lst) = clonal_cloneids

plt_bindratio_tbl = tibble(clone_id = clonal_cloneids, NoneBind_Ratio = atbd_count_lst %>% unlist()) %>% 
  mutate(tag = ifelse(clone_id %in% HBV_specifc_clones, 'HBVspecific', ifelse(clone_id %in% P16_cloneids, 'P3clones', 'P16clones')))

plt_bindratio_tbl$tag = factor(plt_bindratio_tbl$tag, levels = c('HBVspecific', 'P3clones', 'P16clones'))
plt_bindratio_tbl$NoneBind_Ratio[is.na(plt_bindratio_tbl$NoneBind_Ratio)] = 0


require(ggsignif)
plt_bindratio_tbl %>% 
  ggplot(aes(x = tag, y = 1-NoneBind_Ratio)) + 
  geom_boxplot(width = 0.6) +
  geom_signif(comparisons = list(
    c('HBVspecific', 'P3clones'), 
    c('HBVspecific', 'P16clones'),
    c('P3clones', 'P16clones')
  ), y_position = c(1, 1.1, 1.2),
  map_signif_level = function(p) sprintf("p = %.2g", p)) +
  theme_classic(base_size = 20) +
  labs(x = '', y = 'Antibody binding ratio', title = 'All clonal clones')


n_clonesize_cutoff = 20
chosen_clones = names(clonesize_vec)[clonesize_vec > n_clonesize_cutoff]
require(ggsignif)
plt_bindratio_tbl %>% 
  filter(clone_id %in% chosen_clones) %>% 
  ggplot(aes(x = tag, y = 1-NoneBind_Ratio)) + 
  geom_boxplot() +
  geom_signif(comparisons = list(
    c('HBVspecific', 'P3clones'), 
    c('HBVspecific', 'P16clones'),
    c('P3clones', 'P16clones')
  ), y_position = c(1, 1.1, 1.2),
  map_signif_level = function(p) sprintf("p = %.2g", p)) +
  theme_classic(base_size = 20) +
  labs(x = '', y = 'Antibody binding ratio', title = sprintf('Clonal clones with at least %d cells', n_clonesize_cutoff))


```
